### PR TITLE
Rename the Flatpak, fix AppStream metadata

### PR DESCRIPTION
**Pull request by AsciiWolf**
See the following upstream commits:

https://github.com/ioquake/ioq3/commit/e5c688b342b8e7edd88bc670c02c9050e007fcab
https://github.com/ioquake/ioq3/commit/b1e6ef14254fdcb77cbe2f602c22549d3fb0eb78

(Screenshots are not a problem for downstream/Flatpak, so no need to remove or change them.)

@mattiasb Feel free to review.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
One more thing needed for the Flathub submission is creating a ticket [in the official ioquake3 issue tracker](https://github.com/ioquake/ioq3/issues) informing upstream about the Flatpak and asking whether they are interested in co-maintaining it. [Here](https://github.com/f4exb/sdrangel/issues/1355) is an example how to do it.

**Comment by AsciiWolf** [comment]
@mattiasb If you are too busy, I can prepare the Flathub PR myself and submit it on your behalf (and also create the ioquake3 issue regarding their interest in co-maintaining the Flatpak). Please, let me know. Thanks!

**Comment by mattiasb** [comment]
Yeah please do that. Let's just say life happened. Basically fork and go nuts!

**Comment by AsciiWolf** [comment]
@mattiasb https://github.com/flathub/flathub/pull/4519

**Pull request closed without merging**
